# Generated by Django 5.2.4 on 2025-11-08 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0002_article_goal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_type',
            field=models.CharField(choices=[('article', 'Article'), ('news', 'News')], default='article', help_text='Type: Article (user-submitted) or News (from external source)', max_length=20),
        ),
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who submitted this article (null for admin/news articles)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['article_type', '-created_at'], name='finance_app_article_8219b1_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['user', '-created_at'], name='finance_app_user_id_317e6d_idx'),
        ),
    ]
